from datetime import datetime

# ==========================================================
# REPORT GENERATOR
# ==========================================================

def generate_report(results, risk, score, summary):

    report = f"""
============================================================
 Sensitive Data Detection & Compliance Report
============================================================

Generated On :
{datetime.now().strftime("%d-%m-%Y %H:%M:%S")}

============================================================
OVERALL RISK
============================================================

Risk Level : {risk}

Risk Score : {score}

============================================================
SENSITIVE INFORMATION DETECTED
============================================================
"""

    for category, values in results.items():

        report += f"\n{category}\n"
        report += "-" * len(category)
        report += "\n"

        if values:

            for item in values:
                report += f"• {item}\n"

        else:

            report += "No Sensitive Data Found\n"

        report += "\n"

    report += f"""
============================================================
AI COMPLIANCE SUMMARY
============================================================

{summary}

============================================================
END OF REPORT
============================================================

Generated by

Sensitive Data Detection & Compliance Assistant
"""

    return report